import type { Metadata } from 'next';
import { UserProvider } from '../app/Component/userContext';
import './globals.css';
import { ReactNode } from 'react'; 


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Define the props type for RootLayout
interface RootLayoutProps {
  children: ReactNode; // Use ReactNode for children
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <UserProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </UserProvider>
  );
}
